SELECT ?id ?id_id ?id_color_id ?id_color_rgb WHERE {
  ?id_id <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q11173>;
    <http://www.wikidata.org/prop/direct/P462> ?id_color_id.
  OPTIONAL { ?id_color_id <http://www.wikidata.org/prop/direct/P465> ?id_color_rgb. }
}